<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Learning.Auth.Application\Learning.Auth.Application.csproj" />
    <ProjectReference Include="..\Learning.Auth.Domain\Learning.Auth.Domain.csproj" />
  </ItemGroup>
</Project>
